// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNote(arg1:string):Promise<boolean>;

export function GetNotes():Promise<Array<main.Note>>;

export function SaveNote(arg1:string,arg2:string):Promise<main.Note>;
